// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxooEtm7x1m3XRX2iXvgk-Mu4CCQ7N37c',
    appId: '1:1067919102063:web:d90d9a8172d0a8c4d83d9a',
    messagingSenderId: '1067919102063',
    projectId: 'petcare-4d661',
    authDomain: 'petcare-4d661.firebaseapp.com',
    databaseURL: 'https://petcare-4d661-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-4d661.firebasestorage.app',
    measurementId: 'G-L1HRRF9ZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG10LTqkMFu5L_SXvzpdJIsvRnVPYHY-Y',
    appId: '1:1067919102063:android:06499ea203d1e30bd83d9a',
    messagingSenderId: '1067919102063',
    projectId: 'petcare-4d661',
    databaseURL: 'https://petcare-4d661-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-4d661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvxLGIeWKX8x3QfoJ8tc6LvqLk0Fi7as',
    appId: '1:1067919102063:ios:e1db6864a4d92cacd83d9a',
    messagingSenderId: '1067919102063',
    projectId: 'petcare-4d661',
    databaseURL: 'https://petcare-4d661-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-4d661.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNvxLGIeWKX8x3QfoJ8tc6LvqLk0Fi7as',
    appId: '1:1067919102063:ios:e1db6864a4d92cacd83d9a',
    messagingSenderId: '1067919102063',
    projectId: 'petcare-4d661',
    databaseURL: 'https://petcare-4d661-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-4d661.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxooEtm7x1m3XRX2iXvgk-Mu4CCQ7N37c',
    appId: '1:1067919102063:web:32144edc787ac7b3d83d9a',
    messagingSenderId: '1067919102063',
    projectId: 'petcare-4d661',
    authDomain: 'petcare-4d661.firebaseapp.com',
    databaseURL: 'https://petcare-4d661-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-4d661.firebasestorage.app',
    measurementId: 'G-E6Z3TR497D',
  );
}
